name = "TestStyledStrings"
uuid = "cd969f85-f669-4134-a54f-c9eb8964e64e"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[compat]
Jive = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "StyledStrings", "Jive"]
